### ISSUE TITLE
hard to scroll between product images on pc

### ISSUE THREAD

**Issue by Bilalm354** [bilal-and-haffi/aiPersonalisedGifts#29]

**Comment by haffi96** [comment]
i think its kinda hard to tell theres more than one image without the arrows. But also on mobile, arrows look and feel ass

add a 1/5 indicator to show theres more images available

on mobile:
don't show arrows, someone indicate that the user can scroll right and left

**Comment by Bilalm354** [comment]
this was a long time ago. I think its fine now
