### ISSUE TITLE
Add order confirmation page after payment

### ISSUE THREAD

**Issue by Bilalm354** [bilal-and-haffi/aiPersonalisedGifts#40]

**Comment by haffi96** [comment]
can include the printify tracking url 

i.e https://trackorder.site/gAAAAABmEsdEgfqUCKyYT_8Lp4shb_D-6nAYmbvnCr5IyM8WTIGa1CMAy9C4pLhfu4VkBH3-NFNLegpB3_GInu0gaTcFECxEABUV6D-_GWJDYjUIGpsAtfc

**Comment by haffi96** [comment]
potentially also stripe customer portal https://billing.stripe.com/p/session/test_YWNjdF8xT290WU5GTnVFOHU5MnVOLF9Qc2p2MGlNeWR0SUJWQ1RNZnVJQ0ZUc1BleVV3M1I20100K8OtWGKQ
