### ISSUE TITLE
buy a domain on vercel

### ISSUE THREAD

**Issue by Bilalm354** [bilal-and-haffi/aiPersonalisedGifts#50]
# potential ideas
teemaker.com
create your tee

aipparel.org or aipparel.app

**Comment by haffi96** [comment]
vercel domains are more expensive. MIght be cheaper on namecheap or hostinger or cloudflare

cloudflare domains have free perks

**Comment by Bilalm354** [comment]
Ai image apparel

**Comment by Bilalm354** [comment]
www.ai-print-shop.com
